<?php
/**
 * This class is an Exception extension created to distinguish any
 * Exception from the case when an Object of the incorrect type is
 * passed to a function expecting a specific Object type.
 *
 * PHP Version 5
 *
 * @category Errors
 * @package  Loris
 * @author   Rida Abou-Haidar <rida.loris@gmail.com>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link     https://github.com/aces/Loris
 */

/**
 * The LorisIncorrectObjectException class.
 *
 * @category Errors
 * @package  Loris
 * @author   Rida Abou-Haidar <rida.loris@gmail.com>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link     https://github.com/aces/Loris
 */

class LorisIncorrectObjectException extends LorisException
{
}
?>
